batch_size: 1
cudacores: 6
data_dir: ./data/
device: cuda
f_beta: 3.0
log_tb: false
loss_kwargs:
  dist_metric: l2_rbf
  gamma: 2.0
  imbalance: 15
  multiplier: 2.0
  sigma: 0.75
  tau: 0.05
  use_dynamic_alpha: true
loss_name: infonce
lr_scheduler_kwargs:
  eta_min: 0.0
  num_training_steps: 400000
  num_warmup_steps: 10000
lr_scheduler_name: cosine
main_metric: val_AP@0.9
mode: max
model_kwargs:
  W_out_hdim_factor: 1
  act_MLP: SiLU
  block_size: 100
  dropout: 0.0
  h_dim: 48
  h_dim_MLP: 512
  lsh_dims: 3
  n_hashes: 4
  n_layers: 4
  n_layers_MLP: 10
  num_heads: 8
  num_regions: 150
  num_w_per_dist: 10
multiple_gpus: false
num_epochs: 200
num_events: 2500
num_threads: 8
optimizer_kwargs:
  lr: 0.001
  weight_decay: 0.02
optimizer_name: adamw
pileup_density: 200
resume: false
seed: 42
task: tracking
